"""Create activities table

Revision ID: 9c06962cfb75
Revises: 4ec8529c11f4
Create Date: 2023-02-24 15:07:48.778603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '9c06962cfb75'
down_revision = '4ec8529c11f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    deals_table = op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_meeting', sa.Date(), nullable=True),
    sa.Column('next_meeting', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    activities_table = op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_inbound', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###




    op.bulk_insert(deals_table,
        [
            {
                "id":1,
                "name": "Novacy",
                "last_meeting": "2022-12-15",
                "next_meeting": "2023-03-01",
                "owner": "Jane",
                "stage": "Prospecting",
                "amount": 1000
            },
            {
                "id":2,
                "name": "Maya deal",
                "last_meeting": "2022-11-23",
                "next_meeting": "2023-02-28",
                "owner": "Mike",
                "stage": "Negotiation",
                "amount": 5000
            },
            {
                "id":3,
                "name": "Codeme 1",
                "last_meeting": "2022-10-31",
                "next_meeting": "2023-03-15",
                "owner": "Sarah",
                "stage": "Qualification",
                "amount": 10000
            },
            {
                "id":4,
                "name": "Iphone 20s",
                "last_meeting": "2022-09-27",
                "next_meeting": "2023-03-10",
                "owner": "David",
                "stage": "Closing",
                "amount": 53050
            }
        ]
    )
    
    op.bulk_insert(activities_table,
        [
            {
                "id": 1,
                "date": "2023-02-15",
                "is_inbound": 1,
                "title": "Initial call",
                "deal_id":1
            },
            {
                "id": 2,
                "date": "2023-02-01",
                "is_inbound": 0,
                "title": "Follow-up email",
                "deal_id":1
            },
            {
                "id": 3,
                "date": "2023-02-01",
                "is_inbound": 1,
                "title": "Initial call",
                "deal_id":2
            },
            {
                "id": 4,
                "date": "2023-02-11",
                "is_inbound": 0,
                "title": "Follow-up email",
                "deal_id":2
            },
            {
                "id": 5,
                "date": "2023-02-21",
                "is_inbound": 0,
                "title": "Closing email",
                "deal_id":2
            },
            {
                "id": 6,
                "date": "2023-02-03",
                "is_inbound": 1,
                "title": "Initial call",
                "deal_id":3
            },
            {
                "id": 7,
                "date": "2023-02-17",
                "is_inbound": 0,
                "title": "Follow-up email",
                "deal_id":3
            },
            {
                "id": 8,
                "date": "2023-02-17",
                "is_inbound": 0,
                "title": "Closing email",
                "deal_id":3
            },
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('deals')
    # ### end Alembic commands ###
