"""Create activities table

Revision ID: 9c06962cfb75
Revises: 4ec8529c11f4
Create Date: 2023-02-24 15:07:48.778603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c06962cfb75'
down_revision = '4ec8529c11f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_meeting', sa.Date(), nullable=True),
    sa.Column('next_meeting', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_inbound', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('deals')
    # ### end Alembic commands ###
